import React, { useState, useCallback, useEffect, useRef } from 'react';
import { Loader2, Check, X, Wand2, RefreshCcw, Crop } from 'lucide-react';
import ReactCrop, { centerCrop, makeAspectCrop } from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';

// Helper to create the Image object
const createImage = (url) =>
  new Promise((resolve, reject) => {
    const image = new Image();
    image.addEventListener('load', () => resolve(image));
    image.addEventListener('error', (error) => reject(error));
    image.src = url;
  });

// Core function to crop and rotate the image
const getEnhancedImg = async (imageSrc, crop, rotation = 0) => {
  const image = await createImage(imageSrc);
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');

  if (!ctx) return null;

  // Calculate crop rectangle based on original image size vs rendered scale if needed
  // But here we rely on the pixel crop generated by ReactCrop (crop in pixels)
  let cropX = 0;
  let cropY = 0;
  let cropW = image.width;
  let cropH = image.height;

  // ReactCrop provides pixels in 'crop' if it's a pixel crop, otherwise it's percentage.
  // We assume the caller passes the pixel crop.
  if (crop && crop.width > 0 && crop.height > 0) {
      cropX = crop.x;
      cropY = crop.y;
      cropW = crop.width;
      cropH = crop.height;
  }

  // Set the canvas size to the final cropped and rotated size
  if (rotation === 90 || rotation === 270) {
    canvas.width = cropH;
    canvas.height = cropW;
  } else {
    canvas.width = cropW;
    canvas.height = cropH;
  }

  ctx.filter = 'none';

  // Draw with rotation
  ctx.translate(canvas.width / 2, canvas.height / 2);
  ctx.rotate((rotation * Math.PI) / 180);
  
  // Draw only the cropped portion
  ctx.drawImage(
      image,
      cropX, cropY, cropW, cropH,
      -cropW / 2, -cropH / 2, cropW, cropH
  );

  // Reset transform
  ctx.setTransform(1, 0, 0, 1, 0, 0);

  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (!blob) {
          reject(new Error('Canvas is empty'));
          return;
        }
        resolve(blob);
      },
      'image/jpeg',
      0.9
    );
  });
};

export default function DocumentScannerPreview({ file, onCancel, onConfirm }) {
  const [imageSrc, setImageSrc] = useState(null);
  const [rotation, setRotation] = useState(0);
  const [isProcessing, setIsProcessing] = useState(false);
  
  const imgRef = useRef(null);
  const [crop, setCrop] = useState();
  const [completedCrop, setCompletedCrop] = useState();

  useEffect(() => {
    if (file) {
      const reader = new FileReader();
      reader.addEventListener('load', () => setImageSrc(reader.result));
      reader.readAsDataURL(file);
    }
  }, [file]);

  const onImageLoad = useCallback((e) => {
    const { width, height } = e.currentTarget;
    const initialCrop = centerCrop(
        makeAspectCrop({ unit: '%', width: 90, height: 90 }, width / height, width, height),
        width,
        height
    );
    setCrop(initialCrop); 
  }, []);

  const handleConfirm = async () => {
    if (!imageSrc) return;
    setIsProcessing(true);
    
    // Convert rendered crop percentages to actual image pixels if we have a defined crop
    let pixelCrop = null;
    if (completedCrop && completedCrop.width > 0 && completedCrop.height > 0 && imgRef.current) {
        const scaleX = imgRef.current.naturalWidth / imgRef.current.width;
        const scaleY = imgRef.current.naturalHeight / imgRef.current.height;
        
        pixelCrop = {
            unit: 'px',
            x: completedCrop.x * scaleX,
            y: completedCrop.y * scaleY,
            width: completedCrop.width * scaleX,
            height: completedCrop.height * scaleY
        };
    }

    try {
      const enhancedImageBlob = await getEnhancedImg(imageSrc, pixelCrop, rotation);
      const newFile = new File([enhancedImageBlob], 'scanned_slip.jpg', {
        type: 'image/jpeg',
      });
      onConfirm(newFile);
    } catch (e) {
      console.error(e);
      alert('Failed to process image');
    } finally {
      setIsProcessing(false);
    }
  };

  const rotateImage = () => {
    setRotation((prev) => (prev + 90) % 360);
  };

  if (!imageSrc) {
    return (
      <div className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-950/80 backdrop-blur-sm">
        <Loader2 className="h-10 w-10 animate-spin text-white" />
      </div>
    );
  }

  // Dynamic style for preview to reflect what will happen
  const previewStyle = {
    transform: `rotate(${rotation}deg)`,
    filter: 'none',
    maxHeight: '100%',
    maxWidth: '100%',
    objectFit: 'contain',
    transition: 'transform 0.3s ease, filter 0.3s ease'
  };

  return (
    <div className="fixed inset-0 z-[110] flex flex-col bg-slate-950 md:p-6 p-0 text-white backdrop-blur-[2px]">
      <div className="flex flex-1 flex-col overflow-hidden bg-slate-900 shadow-xl md:rounded-2xl border border-slate-700">
        
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 bg-slate-800 border-b border-slate-700">
          <h2 className="text-sm font-bold md:text-base">Document Preview & Crop</h2>
          <button
            onClick={onCancel}
            className="rounded-lg p-1.5 transition hover:bg-slate-700"
            disabled={isProcessing}
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Image Preview Container */}
        <div className="relative flex-1 bg-black flex items-center justify-center overflow-hidden p-4">
          <ReactCrop
              crop={crop}
              onChange={(_, percentCrop) => setCrop(percentCrop)}
              onComplete={(c) => setCompletedCrop(c)}
          >
              <img 
                ref={imgRef}
                src={imageSrc} 
                alt="Document preview" 
                onLoad={onImageLoad}
                style={previewStyle}
                className="max-h-[70vh]"
              />
          </ReactCrop>
        </div>

        {/* Bottom Controls */}
        <div className="bg-slate-800 px-4 py-4 sm:px-6">
          <div className="flex flex-col gap-4">
            <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={rotateImage}
                  className="flex items-center gap-1.5 rounded-lg border border-slate-600 bg-slate-700 px-3 py-2 text-xs font-semibold hover:bg-slate-600"
                >
                  <RefreshCcw className="h-4 w-4" />
                  <span className="hidden sm:inline">Rotate</span>
                </button>
              </div>

              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={onCancel}
                  disabled={isProcessing}
                  className="rounded-lg border border-slate-600 px-4 py-2 text-xs font-semibold text-slate-300 hover:bg-slate-700 disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleConfirm}
                  disabled={isProcessing}
                  className="flex items-center gap-1.5 rounded-lg bg-indigo-600 px-4 py-2 text-xs font-bold text-white shadow-lg hover:bg-indigo-500 disabled:opacity-50"
                >
                  {isProcessing ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Check className="h-4 w-4" />
                  )}
                  {isProcessing ? 'Processing' : 'Done'}
                </button>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
